### ISSUE TITLE
Hook failed

### ISSUE THREAD

**Issue by 2079541547** [ByNameModding/BNM-Android#54]
![image](https://github.com/user-attachments/assets/86435e36-f071-4b78-84fb-8e5a82137015)
![image](https://github.com/user-attachments/assets/1c2cd4b3-d6ab-4062-b8a8-1d65c7260aeb)
I'm using shadowhook to hook the DamageVar method, but the log shows SEGV_MAPERR. Is it because I don't have root permissions or I haven't specified libil2cpp.so?

**Comment by 2079541547** [comment]
![image](https://github.com/user-attachments/assets/0a6b0aee-3e51-4c01-b5be-ca3db699941f)
Unable to load, error：
2024-07-26 02:20:03.522 13660-13857 ByNameModding           com.and.games505.TerrariaPaid        E  Null pointer to the field [Dead]
2024-07-26 02:20:03.522 13660-13857 ByNameModding           com.and.games505.TerrariaPaid        E  An attempt to use dead class!

**Comment by YummyBacon5** [comment]
It seems like you don't have the correct Unity version selected in [GlobalSettings.hpp](https://github.com/ByNameModding/BNM-Android/blob/master/include/BNM/UserSettings/GlobalSettings.hpp#L7) since there are a bunch of warnings.

And the attempt to use dead class error means that the class hasn't been found, which is probably due to the reason above?

Also you'd need to uncomment that `AddOnLoadedEvent` line for your hooks to run.
