### ISSUE TITLE
Using the bugs of shadowhook.

### ISSUE THREAD

**Issue by 2079541547** [ByNameModding/BNM-Android#56]
![d6ff2ebe-195e-40b3-a68e-fb1e4dddebb3](https://github.com/user-attachments/assets/4070494a-98af-4ebf-8eb0-0ad5e6952230)
![image](https://github.com/user-attachments/assets/f1a3e05f-49d2-42c1-9099-724f6de0ce00)
In the shared mode of ShadowHook, the hook function only triggers once, and subsequently directly triggers the original game function.

**Comment by yunli97** [comment]
shadowhook_init(SHADOWHOOK_MODE_UNIQUE, true);

**Comment by 2079541547** [comment]
But I need to use SHARE mode

**Comment by YummyBacon5** [comment]
Then change set the mode to `ShadowHook.Mode.SHARED` instead.

Example from ShadowHook docs: https://github.com/bytedance/android-inline-hook/blob/main/doc/manual.md#example-specify-more-options-through-the-config-parameter

Also do you even need Java to do this? Since your code from before was native

**Comment by 2079541547** [comment]
There is still a problem, but I have found a better solution. Thank you
